export const API_STATUS = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  INDIV_ERR: "INDIV_ERR",
  NONE: "NONE",
};

export const API_TYPES = {
  MENU: "MENU",
  ORDERS: "ORDERS",
  ORDER_DETAILS: "ORDER_DETAILS",
  CHECKOUT: "CHECKOUT",
  TABLE: "TABLE",
  NOTIFICATION: "NOTIFICATION",
  TABLE_CALL: "TABLE_CALL",
  NONE: "NONE",
};
