const CART_REASON_TYPES = {
  ITEMS_UNAVAILABLE: "ITEMS_UNAVAILABLE", //manual - semi status
  KITCHEN_CLOSED: "KITCHEN_CLOSED",
  MANUAL_REJECTION: "MANUAL_REJECTION",
  ORDER_INVALID: "ORDER_INVALID",
  SUCCESS: "SUCCESS", // NOT USEFUL
  ANONYMOUS: "ANONYMOUS",
  NONE: "NONE",
};

module.exports = { CART_REASON_TYPES };
