import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles({
  restInfo: {
    marginTop: "20px",
    paddingBottom: "15px",
    borderRadius: "0px",
    border: "none",
    boxShadow: "none",
    borderBottom: "0.7px solid lightgrey",
  },
  main_text: {
    textAlign: "center",
    fontWeight: "600",
    paddingTop: "8px",
    textTransform: "capitalize",
    opacity: 0.9,
    fontSize: "1.2rem",
    marginTop: "9px",
  },
  light_text: {
    textAlign: "center",
    fontSize: "0.93rem",
    color: "#535665",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    fontWeight: "bold",
    opacity: 0.56,
  },
  icon_img_div: {
    textAlign: "center",
  },
  icon_img: {
    width: "60px",
    padding: "4px",
    border: "1px solid lightgray",
    borderRadius: "7px",
    background: "#f7f2f2",
  },
  dottedSeperator: {
    border: "none",
    borderBottom: "10px solid #ececec",
    width: "100%",
    margin: "20px auto 15px auto",
  },
  infoGrid: {
    borderRight: "1px solid lightgray",
  },
  searchBtn: {
    marginLeft: "auto",
    padding: "6px",
    borderRadius: "50%",
    "&:active": {
      boxShadow: "none",
      backgroundColor: "lightgray",
    },
  },
  itemName: {
    fontWeight: 500,
    fontSize: "1.1rem",
    letterSpacing: "-0.3px",
    fontFamily: "'Proxima Nova', sans-serif",
  },
  itemPrice: {
    fontFamily: "'Open Sans'",
    fontWeight: 500,
    letterSpacing: "-0.2px",
    fontSize: "0.95rem",
    color: "#3e4152",
    "&::before": {
      content: '"\\20B9"',
    },
  },
  itemDesc: {
    marginTop: "14px",
    lineHeight: 1.3,
    color: "rgba(40, 44, 63, 0.45)",
    letterSpacing: "-0.3px",
    fontSize: "0.92rem",
    fontFamily: "'Proxima Nova', sans-serif",
  },
  itemImg: {
    height: "102px",
    width: "116px",
    borderRadius: "6px",
    "&::after": {
      position: "absolute",
      content: "",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(40, 44, 63, 0.05)",
      backgroundBlendMode: "overlay",
      height: "104px",
      borderRadius: "6px",
    },
  },
  categoryName: {
    fontWeight: 500,
    fontSize: "1.15rem",
    color: "#3e4152",
    lineHeight: "1.2",
    letterSpacing: "-0.3px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontFamily: "'Proxima Nova', sans-serif",
  },
  addSubBtn: {
    color: "inherit",
    fontSize: "1.3rem",
    fontWeight: 500,
    background: "inherit",
    border: "none",
    display: "flex",
  },
  repeatBtn: {
    width: "calc(50% - 4%)",
    border: "2px solid #ffa400",
    height: "42px",
    lineHeight: "38px",
    borderRadius: "8px",
    textAlign: "center",
    position: "relative",
    overflow: "hidden",
    textTransform: "uppercase",
    fontWeight: 600,
    display: "flex",
    fontSize: "0.83rem",
  },
});

export default useStyles;
